// Browser-side shell JS injected into the export-html page.
// Array-of-strings format to avoid TypeScript template literal interpolation.

export const WEBUI_SHELL_JS = [
  "(function () {",
  '  "use strict";',
  "",
  "  var STORAGE_FILTER = 'pi-webui:filter';",
  "  var STORAGE_SCROLL = 'pi-webui:scroll';",
  "  var STORAGE_SEARCH = 'pi-webui:tree-search';",
  "  var RELOAD_QUIET_MS = 400;",
  "",
  "  var appState = {",
  "    initialized: false,",
  "    eventSource: null,",
  "    pendingReload: null,",
  "    reloadTimer: null",
  "  };",
  "",
  "  // --- State persistence ---",
  "",
  "  function saveFilter() {",
  "    var active = document.querySelector('.filter-btn.active');",
  "    if (active) {",
  "      try { localStorage.setItem(STORAGE_FILTER, active.dataset.filter || 'default'); } catch (e) {}",
  "    }",
  "  }",
  "",
  "  function saveScroll() {",
  "    try { sessionStorage.setItem(STORAGE_SCROLL, String(window.scrollY)); } catch (e) {}",
  "  }",
  "",
  "  function saveSearch() {",
  "    var input = document.getElementById('tree-search');",
  "    if (input) {",
  "      try { localStorage.setItem(STORAGE_SEARCH, input.value || ''); } catch (e) {}",
  "    }",
  "  }",
  "",
  "  function restoreFilter() {",
  "    try {",
  "      var saved = localStorage.getItem(STORAGE_FILTER);",
  "      if (!saved) return;",
  "      // Delay so template.js init finishes, then click the button",
  "      // This updates both DOM classes and the closure filterMode variable",
  "      setTimeout(function () {",
  "        var btns = document.querySelectorAll('.filter-btn');",
  "        for (var i = 0; i < btns.length; i++) {",
  "          if (btns[i].dataset.filter === saved) {",
  "            btns[i].click();",
  "            break;",
  "          }",
  "        }",
  "      }, 50);",
  "    } catch (e) {}",
  "  }",
  "",
  "  function restoreScroll() {",
  "    try {",
  "      var y = parseInt(sessionStorage.getItem(STORAGE_SCROLL) || '0', 10);",
  "      if (y > 0) {",
  "        window.scrollTo(0, y);",
  "      }",
  "    } catch (e) {}",
  "  }",
  "",
  "  function restoreSearch() {",
  "    try {",
  "      var saved = localStorage.getItem(STORAGE_SEARCH);",
  "      if (!saved) return;",
  "      // Delay so template.js init finishes, then set search input",
  "      setTimeout(function () {",
  "        var input = document.getElementById('tree-search');",
  "        if (input) {",
  "          input.value = saved;",
  "          input.dispatchEvent(new Event('input', { bubbles: true }));",
  "        }",
  "      }, 50);",
  "    } catch (e) {}",
  "  }",
  "",
  "  function trackFilterChanges() {",
  "    var btns = document.querySelectorAll('.filter-btn');",
  "    for (var i = 0; i < btns.length; i++) {",
  "      btns[i].addEventListener('click', function () {",
  "        setTimeout(saveFilter, 50);",
  "      });",
  "    }",
  "  }",
  "",
  "  var scrollSaveTimer = null;",
  "  function trackScroll() {",
  "    window.addEventListener('scroll', function () {",
  "      if (scrollSaveTimer) clearTimeout(scrollSaveTimer);",
  "      scrollSaveTimer = setTimeout(saveScroll, 200);",
  "    }, { passive: true });",
  "  }",
  "",
  "  function trackSearchChanges() {",
  "    var input = document.getElementById('tree-search');",
  "    if (input) {",
  "      input.addEventListener('input', function () {",
  "        setTimeout(saveSearch, 100);",
  "      });",
  "    }",
  "  }",
  "",
  "  function saveAllState() {",
  "    saveFilter();",
  "    saveScroll();",
  "    saveSearch();",
  "  }",
  "",
  "  // --- Session data (raw markdown from pi export-html) ---",
  "",
  "  var entriesById = null;",
  "",
  "  function loadSessionData() {",
  "    try {",
  "      var el = document.getElementById('session-data');",
  "      if (!el) return;",
  "      var base64 = el.textContent;",
  "      var binary = atob(base64);",
  "      var bytes = new Uint8Array(binary.length);",
  "      for (var i = 0; i < binary.length; i++) {",
  "        bytes[i] = binary.charCodeAt(i);",
  "      }",
  "      var data = JSON.parse(new TextDecoder('utf-8').decode(bytes));",
  "      entriesById = new Map();",
  "      if (data.entries) {",
  "        for (var j = 0; j < data.entries.length; j++) {",
  "          entriesById.set(data.entries[j].id, data.entries[j]);",
  "        }",
  "      }",
  "    } catch (e) {",
  "      console.error('Failed to load session data:', e);",
  "    }",
  "  }",
  "",
  "  function extractEntryMarkdown(entryId) {",
  "    if (!entriesById) loadSessionData();",
  "    var entry = entriesById ? entriesById.get(entryId) : null;",
  "    if (!entry) return null;",
  "    switch (entry.type) {",
  "      case 'message': {",
  "        var msg = entry.message;",
  "        if (msg.role === 'user') {",
  "          var content = msg.content;",
  "          var text = typeof content === 'string' ? content :",
  "            content.filter(function (c) { return c.type === 'text'; }).map(function (c) { return c.text; }).join('\\n');",
  "          return text.trim() || null;",
  "        }",
  "        if (msg.role === 'assistant') {",
  "          var parts = [];",
  "          for (var k = 0; k < msg.content.length; k++) {",
  "            var block = msg.content[k];",
  "            if (block.type === 'text' && block.text) {",
  "              parts.push(block.text);",
  "            }",
  "          }",
  "          return parts.join('\\n\\n') || null;",
  "        }",
  "        if (msg.role === 'bashExecution') {",
  "          var parts2 = [];",
  "          if (msg.command) parts2.push('$ ' + msg.command);",
  "          if (msg.output) parts2.push(msg.output);",
  "          return parts2.join('\\n\\n') || null;",
  "        }",
  "        if (msg.role === 'toolResult') {",
  "          var text2 = msg.content.filter(function (c) { return c.type === 'text'; }).map(function (c) { return c.text; }).join('\\n');",
  "          return text2.trim() || null;",
  "        }",
  "        return null;",
  "      }",
  "      case 'branch_summary':",
  "        return entry.summary;",
  "      case 'custom_message': {",
  "        var content2 = entry.content;",
  "        var text3 = typeof content2 === 'string' ? content2 :",
  "          content2.filter(function (c) { return c.type === 'text'; }).map(function (c) { return c.text; }).join('\\n');",
  "        return text3.trim() || null;",
  "      }",
  "      default:",
  "        return null;",
  "    }",
  "  }",
  "",
  "  // --- UI injection ---",
  "",
  "  function injectControlBar() {",
  "    if (document.getElementById('webui-control-bar')) return;",
  "    var content = document.getElementById('content');",
  "    if (!content) return;",
  "",
  "    var bar = document.createElement('div');",
  "    bar.id = 'webui-control-bar';",
  "    bar.innerHTML = [",
  "      '<div class=\"webui-status\">',",
  "      '  <span id=\"webui-connection\">connecting...</span>',",
  "      '  <span id=\"webui-streaming\"></span>',",
  "      '</div>',",
  "      '<form id=\"webui-prompt-form\" class=\"webui-prompt-form\">',",
  "      '  <textarea id=\"webui-prompt-input\" rows=\"3\" placeholder=\"Send a prompt to pi...\"></textarea>',",
  "      '  <div class=\"webui-prompt-actions\">',",
  "      '    <button type=\"button\" id=\"webui-abort\">Abort</button>',",
  "      '    <button type=\"submit\">Send</button>',",
  "      '  </div>',",
  "      '</form>'",
  "    ].join('');",
  "",
  "    content.appendChild(bar);",
  "",
  "    var scrollToBottomBtn = document.createElement('button');",
  "    scrollToBottomBtn.id = 'webui-scroll-bottom';",
  "    scrollToBottomBtn.title = 'Scroll to bottom';",
  "    scrollToBottomBtn.textContent = '\\u25BC';",
  "    document.body.appendChild(scrollToBottomBtn);",
  "",
  "    document.getElementById('webui-abort').addEventListener('click', function () {",
  "      fetch('/__webui/api/abort', { method: 'POST' });",
  "    });",
  "",
  "    document.getElementById('webui-prompt-form').addEventListener('submit', async function (event) {",
  "      event.preventDefault();",
  "      var input = document.getElementById('webui-prompt-input');",
  "      var message = input.value.trim();",
  "      if (!message) return;",
  "      input.value = '';",
  "      autoResize(input);",
  "      await fetch('/__webui/api/prompt', {",
  "        method: 'POST',",
  "        headers: { 'content-type': 'application/json' },",
  "        body: JSON.stringify({ message: message })",
  "      });",
  "      scheduleReload();",
  "    });",
  "",
  "    function autoResize(el) {",
  "      el.style.height = 'auto';",
  "      var newHeight = Math.min(Math.max(el.scrollHeight, 48), 200);",
  "      el.style.height = newHeight + 'px';",
  "    }",
  "",
  "    document.getElementById('webui-prompt-input').addEventListener('input', function () {",
  "      autoResize(this);",
  "    });",
  "  }",
  "",
  "  function copyToClipboard(text, button) {",
  "    if (navigator.clipboard && navigator.clipboard.writeText) {",
  "      navigator.clipboard.writeText(text).then(function () {",
  "        showCopied(button);",
  "      }).catch(function () {",
  "        fallbackCopy(text, button);",
  "      });",
  "      return;",
  "    }",
  "    fallbackCopy(text, button);",
  "  }",
  "",
  "  function fallbackCopy(text, button) {",
  "    try {",
  "      var ta = document.createElement('textarea');",
  "      ta.value = text;",
  "      ta.style.position = 'fixed';",
  "      ta.style.opacity = '0';",
  "      document.body.appendChild(ta);",
  "      ta.select();",
  "      document.execCommand('copy');",
  "      document.body.removeChild(ta);",
  "      showCopied(button);",
  "    } catch (e) {",
  "      console.error('Failed to copy:', e);",
  "    }",
  "  }",
  "",
  "  function showCopied(button) {",
  "    var orig = button.innerHTML;",
  "    button.innerHTML = '\\u2713';",
  "    button.classList.add('copied');",
  "    setTimeout(function () {",
  "      button.innerHTML = orig;",
  "      button.classList.remove('copied');",
  "    }, 1500);",
  "  }",
  "",
  "  function injectCopyMarkdownButtons() {",
  "    var messages = document.querySelectorAll('.user-message, .assistant-message');",
  "    for (var i = 0; i < messages.length; i++) {",
  "      var msg = messages[i];",
  "      if (msg.querySelector('.copy-md-btn')) continue;",
  "      var entryId = msg.id ? msg.id.replace(/^entry-/, '') : null;",
  "      if (!entryId) continue;",
  "      if (msg.classList.contains('assistant-message') && !msg.querySelector('.assistant-text')) continue;",
  "      var btn = document.createElement('button');",
  "      btn.className = 'copy-md-btn';",
  "      btn.title = 'Copy as markdown';",
  "      btn.innerHTML = '<svg width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"/><polyline points=\"14 2 14 8 20 8\"/><line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"/><line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"/><polyline points=\"10 9 9 9 8 9\"/></svg>';",
  "      btn.addEventListener('click', (function (id) {",
  "        return function (e) {",
  "          e.preventDefault();",
  "          e.stopPropagation();",
  "          var md = extractEntryMarkdown(id);",
  "          if (md) copyToClipboard(md, btn);",
  "        };",
  "      })(entryId));",
  "      msg.insertBefore(btn, msg.firstChild.nextSibling);",
  "    }",
  "  }",
  "",
  "  function injectStyles() {",
  "    if (document.getElementById('webui-style')) return;",
  "    var style = document.createElement('style');",
  "    style.id = 'webui-style';",
  "    style.textContent = [",
  "      '#webui-control-bar { padding: 16px; border-top: 1px solid var(--dim); background: var(--exportCardBg); position: sticky; bottom: 0; z-index: 20; margin-top: auto; }',",
  "      '.webui-status { display: flex; flex-direction: column; gap: 0; color: var(--muted); font-size: 11px; margin-bottom: 8px; }',",
  "      '.webui-prompt-form { display: flex; flex-direction: column; gap: 8px; }',",
  "      '#webui-prompt-input { width: 100%; resize: none; border: 1px solid var(--dim); border-radius: 4px; background: var(--body-bg); color: var(--text); font: inherit; font-size: 13px; padding: 8px 10px; line-height: 1.4; min-height: 48px; max-height: 200px; overflow-y: auto; box-sizing: border-box; }',",
  "      '.webui-prompt-actions { display: flex; gap: 8px; justify-content: flex-end; }',",
  "      '.webui-prompt-actions button { background: var(--accent); color: var(--body-bg); border: none; border-radius: 4px; padding: 6px 16px; cursor: pointer; font: inherit; font-size: 12px; }',",
  "      '.webui-prompt-actions button:hover { opacity: 0.92; }',",
  "      '.webui-prompt-actions button:nth-child(1) { background: var(--dim); color: var(--text); }',",
  "      '.webui-prompt-actions button:nth-child(1):hover { background: var(--muted); }',",
  "",
  "      '.copy-md-btn { position: absolute; top: 8px; right: 40px; width: 28px; height: 28px; padding: 6px; background: var(--container-bg); border: 1px solid var(--dim); border-radius: 4px; color: var(--muted); cursor: pointer; opacity: 0; transition: opacity 0.15s, background 0.15s, color 0.15s; display: flex; align-items: center; justify-content: center; z-index: 10; }',",
  "      '.user-message:hover .copy-md-btn, .assistant-message:hover .copy-md-btn { opacity: 1; }',",
  "      '.copy-md-btn:hover { background: var(--accent); color: var(--body-bg); border-color: var(--accent); }',",
  "      '.copy-md-btn.copied { background: var(--success, #22c55e); color: white; border-color: var(--success, #22c55e); }',",
  "",
  "      '#webui-scroll-bottom { position: fixed; bottom: 160px; right: 24px; z-index: 30; width: 40px; height: 40px; border-radius: 50%; border: 1px solid var(--dim); background: var(--exportCardBg); color: var(--text); font-size: 18px; cursor: pointer; display: none; align-items: center; justify-content: center; box-shadow: 0 2px 8px rgba(0,0,0,0.3); opacity: 0; transition: opacity 0.2s; }',",
  "      '#webui-scroll-bottom.visible { display: flex; opacity: 0.85; }',",
  "      '#webui-scroll-bottom:hover { opacity: 1; background: var(--selectedBg); }'",
  "    ].join('\\n');",
  "    document.head.appendChild(style);",
  "  }",
  "",
  "  function scrollToBottom() {",
  "    window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'smooth' });",
  "  }",
  "",
  "  function setupScrollToBottomButton() {",
  "    var btn = document.getElementById('webui-scroll-bottom');",
  "    if (!btn) return;",
  "    btn.addEventListener('click', scrollToBottom);",
  "",
  "    var scrollTolerance = 120;",
  "",
  "    function onScroll() {",
  "      var distanceFromBottom = document.documentElement.scrollHeight - window.scrollY - window.innerHeight;",
  "      if (distanceFromBottom > scrollTolerance) {",
  "        btn.classList.add('visible');",
  "      } else {",
  "        btn.classList.remove('visible');",
  "      }",
  "    }",
  "",
  "    window.addEventListener('scroll', onScroll, { passive: true });",
  "    onScroll();",
  "  }",
  "",
  "  function syncStatus(runtime) {",
  "    var connection = document.getElementById('webui-connection');",
  "    var streaming = document.getElementById('webui-streaming');",
  "    if (connection) {",
  "      var sessionLabel = runtime.sessionName || runtime.sessionFile || runtime.sessionId || 'live session';",
  "      connection.textContent = 'connected - ' + sessionLabel;",
  "    }",
  "    if (streaming) {",
  "      streaming.textContent = runtime.isStreaming ? 'streaming...' : 'idle';",
  "      streaming.style.color = runtime.isStreaming ? 'var(--warning)' : 'var(--success)';",
  "    }",
  "  }",
  "",
  "  // --- Reload with state preservation ---",
  "",
  "  function scheduleReload() {",
  "    saveAllState();",
  "    if (appState.reloadTimer) return;",
  "    appState.reloadTimer = setTimeout(function () {",
  "      appState.reloadTimer = null;",
  "      window.location.reload();",
  "    }, RELOAD_QUIET_MS);",
  "  }",
  "",
  "  function connectEvents() {",
  "    if (appState.eventSource) appState.eventSource.close();",
  "    var source = new EventSource('/__webui/events');",
  "    appState.eventSource = source;",
  "",
  "    source.addEventListener('open', function () {",
  "      var connection = document.getElementById('webui-connection');",
  "      if (connection) connection.textContent = 'connected';",
  "    });",
  "",
  "    source.addEventListener('snapshot', function (event) {",
  "      var payload = JSON.parse(event.data);",
  "      syncStatus(payload.runtime);",
  "    });",
  "",
  "    source.addEventListener('runtime', function (event) {",
  "      var payload = JSON.parse(event.data);",
  "      syncStatus(payload);",
  "    });",
  "",
  "    source.addEventListener('session', function () {",
  "      scheduleReload();",
  "    });",
  "",
  "    source.addEventListener('agent', function () {",
  "      scheduleReload();",
  "    });",
  "",
  "    source.addEventListener('message', function () {",
  "      scheduleReload();",
  "    });",
  "",
  "    source.addEventListener('tool', function () {",
  "      scheduleReload();",
  "    });",
  "",
  "    source.onerror = function () {",
  "      var connection = document.getElementById('webui-connection');",
  "      if (connection) connection.textContent = 'reconnecting...';",
  "    };",
  "  }",
  "",
  "  function boot() {",
  "    if (appState.initialized) return;",
  "    appState.initialized = true;",
  "    injectStyles();",
  "    injectControlBar();",
  "    injectCopyMarkdownButtons();",
  "    setupScrollToBottomButton();",
  "    connectEvents();",
  "",
  "    // Delay state restore so template.js init finishes first",
  "    setTimeout(function () {",
  "      restoreFilter();",
  "      restoreSearch();",
  "    }, 50);",
  "    trackFilterChanges();",
  "    trackSearchChanges();",
  "    trackScroll();",
  "",
  "    // If no saved scroll, go to bottom",
  "    var savedScroll = parseInt(sessionStorage.getItem(STORAGE_SCROLL) || '0', 10);",
  "    if (savedScroll > 0) {",
  "      requestAnimationFrame(function () { window.scrollTo(0, savedScroll); });",
  "    } else {",
  "      requestAnimationFrame(scrollToBottom);",
  "    }",
  "  }",
  "",
  "  if (document.readyState === 'loading') {",
  "    document.addEventListener('DOMContentLoaded', function () { boot(); }, { once: true });",
  "  } else {",
  "    boot();",
  "  }",
  "})();",
].join("\n");
