/** Browser script for SSM. Array join avoids TS template interpolation. */
export const SSM_PAGE_JS = [
	"(function () {",
	'"use strict";',
	"var state = { catalog: null, folder: null, selected: null, q: '', showArchived: false };",
	"",
	"function $(id) { return document.getElementById(id); }",
	"function fmt(iso) {",
	"  if (!iso) return '—';",
	"  try { return new Date(iso).toLocaleString(); } catch (e) { return iso; }",
	"}",
	"function shortPath(p) {",
	"  if (!p) return '(unknown)';",
	"  return p;",
	"}",
	"function shortId(id) { return (id || '').slice(0, 8); }",
	"function matches(s, q) {",
	"  if (!q) return true;",
	"  q = q.toLowerCase();",
	"  var hay = [s.name, s.id, s.path, s.cwd, s.firstMessage].join(' ').toLowerCase();",
	"  return hay.indexOf(q) !== -1;",
	"}",
	"function sessionsForView() {",
	"  if (!state.catalog) return [];",
	"  return state.catalog.sessions.filter(function (s) {",
	"    if (!state.showArchived && s.archived) return false;",
	"    if (state.folder && (s.cwd || '(unknown)') !== state.folder) return false;",
	"    return matches(s, state.q);",
	"  });",
	"}",
	"function isLive(s) { return !!(s && s.live); }",
	"function escapeHtml(s) {",
	"  return String(s == null ? '' : s)",
	"    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')",
	"    .replace(/\"/g, '&quot;').replace(/'/g, '&#39;');",
	"}",
	"function row(k, v) { return '<dt>' + k + '</dt><dd>' + escapeHtml(v) + '</dd>'; }",
	"function viewUrl(path) { return '/view?path=' + encodeURIComponent(path); }",
	"function liveUrl(s) { return '/live?id=' + encodeURIComponent(s.id || s.path); }",
	"function openSession(s) {",
	"  if (!s) return;",
	"  window.open(s.live ? liveUrl(s) : viewUrl(s.path), '_blank', 'noopener,noreferrer');",
	"}",
	"function sessionByPath(path) {",
	"  if (!state.catalog) return null;",
	"  return state.catalog.sessions.find(function (s) { return s.path === path; }) || null;",
	"}",
	"function selectPath(path) {",
	"  state.selected = sessionByPath(path);",
	"  renderSessions();",
	"  renderDetail();",
	"}",
	"function renderStats() {",
	"  var c = state.catalog;",
	"  if (!c) { $('stats').textContent = 'Loading…'; return; }",
	"  var run = c.liveCount || 0;",
	"  $('stats').innerHTML =",
	"    '<span>' + c.folderCount + ' folders</span>' +",
	"    '<span>' + c.sessionCount + ' sessions</span>' +",
	"    '<span>' + c.archivedCount + ' archived</span>' +",
	"    (run ? '<span class=\"live-pill\">' + run + ' running</span>' : '') +",
	"    '<span>loaded ' + fmt(c.loadedAt) + '</span>';",
	"}",
	"function renderFolders() {",
	"  var el = $('folders');",
	"  if (!state.catalog) { el.innerHTML = ''; return; }",
	"  var html = '';",
	"  html += '<button type=\"button\" class=\"folder' + (!state.folder ? ' active' : '') + '\" data-cwd=\"\">';",
	"  html += '<div class=\"path\">All folders</div>';",
	"  html += '<div class=\"meta\">' + state.catalog.sessionCount + ' sessions</div></button>';",
	"  state.catalog.folders.forEach(function (f) {",
	"    var active = state.folder === f.cwd ? ' active' : '';",
	"    html += '<button type=\"button\" class=\"folder' + active + '\" data-cwd=\"' + encodeURIComponent(f.cwd) + '\">';",
	"    html += '<div class=\"path\">' + escapeHtml(shortPath(f.cwd)) + '</div>';",
	"    html += '<div class=\"meta\">' + f.activeCount + ' active · ' + f.archivedCount + ' archived · ' + fmt(f.latestModified) + '</div>';",
	"    html += '</button>';",
	"  });",
	"  el.innerHTML = html;",
	"}",
	"function renderSessions() {",
	"  var el = $('sessions');",
	"  var list = sessionsForView();",
	"  if (!list.length) { el.innerHTML = '<p class=\"empty\" style=\"padding:0.5rem\">No sessions.</p>'; return; }",
	"  var html = '';",
	"  list.forEach(function (s) {",
	"    var active = state.selected && state.selected.path === s.path ? ' active' : '';",
	"    html += '<div class=\"session-row' + active + '\" data-path=\"' + encodeURIComponent(s.path) + '\">';",
	"    html += '<button type=\"button\" class=\"session-select\" data-path=\"' + encodeURIComponent(s.path) + '\">';",
	"    html += '<div class=\"title\">';",
	"    if (isLive(s)) html += '<span class=\"badge live\">running</span>';",
	"    if (s.archived) html += '<span class=\"badge archived\">archived</span>';",
	"    html += escapeHtml(shortId(s.id) + (s.name ? ' \u2014 ' + s.name : '')) + '</div>';",
	"    html += '<div class=\"meta\">' + s.messageCount + ' msgs · ' + fmt(s.modified) + '</div>';",
	"    html += '<div class=\"preview\">' + escapeHtml(s.firstMessage) + '</div>';",
	"    html += '</button>';",
	"    html += '</div>';",
	"  });",
	"  el.innerHTML = html;",
	"}",
	"function renderDetail() {",
	"  var el = $('detail');",
	"  var s = state.selected;",
	"  if (!s) { el.innerHTML = '<p class=\"empty\">Select a session.</p>'; return; }",
	"  var html = '';",
	"  html += '<h2>' + escapeHtml(s.name || '(unnamed)') + '</h2>';",
	"  html += '<div class=\"actions\">';",
	"  html += '<button type=\"button\" class=\"primary\" id=\"open-view\">' + (s.live ? 'Open running' : 'Open view') + '</button>';",
	"  html += '<button type=\"button\" id=\"copy-cmd\">Copy resume command</button>';",
	"  if (s.archived) html += '<button type=\"button\" id=\"unarchive\">Unarchive</button>';",
	"  else html += '<button type=\"button\" id=\"archive\">Archive</button>';",
	"  if (!s.live) html += '<button type=\"button\" class=\"danger\" id=\"delete-session\">Delete</button>';",
	"  html += '</div>';",
	"  html += '<div class=\"preview-box\">' + escapeHtml(s.firstMessage) + '</div>';",
	"  html += '<dl>';",
	"  html += row('id', s.id);",
	"  if (s.name) html += row('name', s.name);",
	"  html += row('cwd', s.cwd || '(unknown)');",
	"  html += row('path', s.path);",
	"  html += row('created', fmt(s.created));",
	"  html += row('modified', fmt(s.modified));",
	"  html += row('messages', String(s.messageCount));",
	"  html += row('status', s.archived ? ('archived ' + fmt(s.archivedAt)) : (isLive(s) ? 'pi process running' : 'on disk'));",
	"  html += '</dl>';",
	"  html += '<p class=\"sub\" style=\"margin:0 0 0.35rem;color:var(--muted);font-size:0.8rem\">Running sessions open on this port at /live. Others are read-only snapshots.</p>';",
	"  html += '<code class=\"cmd\" id=\"cmd\">' + escapeHtml(s.resumeCommand) + '</code>';",
	"  el.innerHTML = html;",
	"}",
	"function renderAll() { renderStats(); renderFolders(); renderSessions(); renderDetail(); }",
	"async function loadCatalog(refresh) {",
	"  var url = refresh ? '/api/catalog?refresh=1' : '/api/catalog';",
	"  var res = await fetch(url);",
	"  if (!res.ok) throw new Error('catalog failed: ' + res.status);",
	"  state.catalog = await res.json();",
	"  if (state.selected) {",
	"    state.selected = state.catalog.sessions.find(function (s) { return s.path === state.selected.path; }) || null;",
	"  }",
	"  renderAll();",
	"}",
	"async function post(path, body) {",
	"  var res = await fetch(path, {",
	"    method: 'POST',",
	"    headers: { 'content-type': 'application/json' },",
	"    body: JSON.stringify(body || {})",
	"  });",
	"  var data = await res.json().catch(function () { return {}; });",
	"  if (!res.ok) throw new Error(data.error || ('request failed: ' + res.status));",
	"  return data;",
	"}",
	"$('refresh').addEventListener('click', function () {",
	"  loadCatalog(true).catch(function (e) { alert(e.message); });",
	"});",
	"$('q').addEventListener('input', function (e) {",
	"  state.q = e.target.value || '';",
	"  renderSessions();",
	"});",
	"$('show-archived').addEventListener('change', function (e) {",
	"  state.showArchived = !!e.target.checked;",
	"  renderSessions();",
	"});",
	"$('folders').addEventListener('click', function (e) {",
	"  var btn = e.target.closest('button.folder');",
	"  if (!btn) return;",
	"  var cwd = btn.getAttribute('data-cwd') || '';",
	"  state.folder = cwd ? decodeURIComponent(cwd) : null;",
	"  renderFolders();",
	"  renderSessions();",
	"});",
	"$('sessions').addEventListener('click', function (e) {",
	"  var selectBtn = e.target.closest('button.session-select');",
	"  if (!selectBtn || !state.catalog) return;",
	"  selectPath(decodeURIComponent(selectBtn.getAttribute('data-path') || ''));",
	"});",
	"$('detail').addEventListener('click', function (e) {",
	"  var t = e.target;",
	"  if (!state.selected) return;",
	"  if (t.id === 'open-view') {",
	"    openSession(state.selected);",
	"    return;",
	"  }",
	"  if (t.id === 'copy-cmd') {",
	"    var cmd = state.selected.resumeCommand;",
	"    if (navigator.clipboard && navigator.clipboard.writeText) {",
	"      navigator.clipboard.writeText(cmd).then(function () {",
	"        t.textContent = 'Copied';",
	"        setTimeout(function () { t.textContent = 'Copy resume command'; }, 1200);",
	"      });",
	"    } else {",
	"      prompt('Copy command:', cmd);",
	"    }",
	"    return;",
	"  }",
	"  if (t.id === 'archive' || t.id === 'unarchive') {",
	"    var api = t.id === 'archive' ? '/api/archive' : '/api/unarchive';",
	"    post(api, { path: state.selected.path }).then(function (data) {",
	"      if (data.catalog) state.catalog = data.catalog;",
	"      if (state.selected && state.catalog) {",
	"        state.selected = state.catalog.sessions.find(function (s) {",
	"          return s.path === state.selected.path;",
	"        }) || null;",
	"      }",
	"      renderAll();",
	"    }).catch(function (err) { alert(err.message); });",
	"  }",
	"  if (t.id === 'delete-session') {",
	"    if (!confirm('Permanently delete this session file? (trash CLI used when available)')) return;",
	"    post('/api/delete', { path: state.selected.path }).then(function (data) {",
	"      state.selected = null;",
	"      if (data.catalog) state.catalog = data.catalog;",
	"      renderAll();",
	"    }).catch(function (err) { alert(err.message); });",
	"  }",
	"});",
	"loadCatalog(false).catch(function (e) {",
	"  $('stats').textContent = 'Failed: ' + e.message;",
	"});",
	"})();",
].join("\n");
